server:
  port: 8081

spring:
  application:
    name: main-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: lol_event
        format_sql: true
        show_sql: false
    open-in-view: false
  flyway:
    schemas:
      - lol_event
    default-schema: lol_event

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

riot:
  api:
    key: ${RIOT_API_KEY:}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
