server:
  port: 8081

spring:
  application:
    name: main-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: lol_event
        format_sql: true
        show_sql: false
    open-in-view: false
  flyway:
    schemas:
      - lol_event
    default-schema: lol_event

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, loggers, env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms, 1s

riot:
  api:
    key: ${RIOT_API_KEY:}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
