package com.gijun.main.application.dto.match.command

import com.gijun.main.domain.model.match.Match
import com.gijun.main.domain.model.match.MatchParticipant
import com.gijun.main.domain.model.match.MatchTeam

data class SaveMatchesCommand(val matches: List<MatchInput>)

data class MatchInput(
    val matchId: String,
    val queueId: Int,
    val gameCreation: Long,
    val gameDuration: Int,
    val gameMode: String? = null,
    val gameType: String? = null,
    val gameVersion: String? = null,
    val mapId: Int? = null,
    val seasonId: Int? = null,
    val platformId: String? = null,
    val participants: List<ParticipantInput>,
    val teams: List<TeamInput> = emptyList()
) {
    fun toDomain() = Match(
        matchId = matchId, queueId = queueId,
        gameCreation = gameCreation, gameDuration = gameDuration,
        gameMode = gameMode, gameType = gameType, gameVersion = gameVersion,
        mapId = mapId, seasonId = seasonId, platformId = platformId,
        participants = participants.map { it.toDomain() }.toMutableList(),
        teams = teams.map { it.toDomain() }.toMutableList()
    )
}

data class ParticipantInput(
    val puuid: String?,
    val riotId: String,
    val champion: String,
    val championId: Int = 0,
    val team: String,
    val teamId: Int = 0,
    val spell1Id: Int = 0,
    val spell2Id: Int = 0,
    val win: Boolean,
    val kills: Int = 0,
    val deaths: Int = 0,
    val assists: Int = 0,
    val damage: Int = 0,
    val cs: Int = 0,
    val gold: Int = 0,
    val visionScore: Int = 0,
    val champLevel: Int = 0,
    val doubleKills: Int = 0,
    val tripleKills: Int = 0,
    val quadraKills: Int = 0,
    val pentaKills: Int = 0,
    val unrealKills: Int = 0,
    val killingSprees: Int = 0,
    val largestKillingSpree: Int = 0,
    val largestMultiKill: Int = 0,
    val largestCriticalStrike: Int = 0,
    val longestTimeSpentLiving: Int = 0,
    val firstBloodKill: Boolean = false,
    val firstBloodAssist: Boolean = false,
    val firstTowerKill: Boolean = false,
    val firstTowerAssist: Boolean = false,
    val firstInhibitorKill: Boolean = false,
    val firstInhibitorAssist: Boolean = false,
    val inhibitorKills: Int = 0,
    val turretKills: Int = 0,
    val wardsKilled: Int = 0,
    val wardsPlaced: Int = 0,
    val sightWardsBoughtInGame: Int = 0,
    val visionWardsBoughtInGame: Int = 0,
    val item0: Int = 0, val item1: Int = 0, val item2: Int = 0, val item3: Int = 0,
    val item4: Int = 0, val item5: Int = 0, val item6: Int = 0,
    val perk0: Int = 0, val perk0Var1: Int = 0, val perk0Var2: Int = 0, val perk0Var3: Int = 0,
    val perk1: Int = 0, val perk1Var1: Int = 0, val perk1Var2: Int = 0, val perk1Var3: Int = 0,
    val perk2: Int = 0, val perk2Var1: Int = 0, val perk2Var2: Int = 0, val perk2Var3: Int = 0,
    val perk3: Int = 0, val perk3Var1: Int = 0, val perk3Var2: Int = 0, val perk3Var3: Int = 0,
    val perk4: Int = 0, val perk4Var1: Int = 0, val perk4Var2: Int = 0, val perk4Var3: Int = 0,
    val perk5: Int = 0, val perk5Var1: Int = 0, val perk5Var2: Int = 0, val perk5Var3: Int = 0,
    val perkPrimaryStyle: Int = 0,
    val perkSubStyle: Int = 0,
    val magicDamageDealt: Int = 0, val magicDamageDealtToChampions: Int = 0, val magicalDamageTaken: Int = 0,
    val physicalDamageDealt: Int = 0, val physicalDamageDealtToChampions: Int = 0, val physicalDamageTaken: Int = 0,
    val trueDamageDealt: Int = 0, val trueDamageDealtToChampions: Int = 0, val trueDamageTaken: Int = 0,
    val totalDamageDealt: Int = 0, val totalDamageDealtToChampions: Int = 0, val totalDamageTaken: Int = 0,
    val damageDealtToObjectives: Int = 0, val damageDealtToTurrets: Int = 0, val damageSelfMitigated: Int = 0,
    val totalHeal: Int = 0, val totalUnitsHealed: Int = 0,
    val timeCCingOthers: Int = 0, val totalTimeCrowdControlDealt: Int = 0,
    val neutralMinionsKilled: Int = 0, val neutralMinionsKilledTeamJungle: Int = 0, val neutralMinionsKilledEnemyJungle: Int = 0,
    val combatPlayerScore: Int = 0, val objectivePlayerScore: Int = 0,
    val totalPlayerScore: Int = 0, val totalScoreRank: Int = 0,
    val gameEndedInSurrender: Boolean = false, val gameEndedInEarlySurrender: Boolean = false,
    val causedEarlySurrender: Boolean = false, val earlySurrenderAccomplice: Boolean = false,
    val teamEarlySurrendered: Boolean = false,
    val playerAugment1: Int = 0, val playerAugment2: Int = 0, val playerAugment3: Int = 0,
    val playerAugment4: Int = 0, val playerAugment5: Int = 0, val playerAugment6: Int = 0,
    val playerSubteamId: Int = 0, val subteamPlacement: Int = 0, val roleBoundItem: Int = 0,
    val lane: String? = null,
    val role: String? = null
) {
    fun toDomain() = MatchParticipant(
        puuid = puuid, riotId = riotId, champion = champion, championId = championId,
        team = team, teamId = teamId, spell1Id = spell1Id, spell2Id = spell2Id, win = win,
        kills = kills, deaths = deaths, assists = assists, damage = damage, cs = cs, gold = gold, visionScore = visionScore,
        champLevel = champLevel, doubleKills = doubleKills, tripleKills = tripleKills,
        quadraKills = quadraKills, pentaKills = pentaKills, unrealKills = unrealKills,
        killingSprees = killingSprees, largestKillingSpree = largestKillingSpree,
        largestMultiKill = largestMultiKill, largestCriticalStrike = largestCriticalStrike,
        longestTimeSpentLiving = longestTimeSpentLiving,
        firstBloodKill = firstBloodKill, firstBloodAssist = firstBloodAssist,
        firstTowerKill = firstTowerKill, firstTowerAssist = firstTowerAssist,
        firstInhibitorKill = firstInhibitorKill, firstInhibitorAssist = firstInhibitorAssist,
        inhibitorKills = inhibitorKills, turretKills = turretKills,
        wardsKilled = wardsKilled, wardsPlaced = wardsPlaced,
        sightWardsBoughtInGame = sightWardsBoughtInGame, visionWardsBoughtInGame = visionWardsBoughtInGame,
        item0 = item0, item1 = item1, item2 = item2, item3 = item3, item4 = item4, item5 = item5, item6 = item6,
        perk0 = perk0, perk0Var1 = perk0Var1, perk0Var2 = perk0Var2, perk0Var3 = perk0Var3,
        perk1 = perk1, perk1Var1 = perk1Var1, perk1Var2 = perk1Var2, perk1Var3 = perk1Var3,
        perk2 = perk2, perk2Var1 = perk2Var1, perk2Var2 = perk2Var2, perk2Var3 = perk2Var3,
        perk3 = perk3, perk3Var1 = perk3Var1, perk3Var2 = perk3Var2, perk3Var3 = perk3Var3,
        perk4 = perk4, perk4Var1 = perk4Var1, perk4Var2 = perk4Var2, perk4Var3 = perk4Var3,
        perk5 = perk5, perk5Var1 = perk5Var1, perk5Var2 = perk5Var2, perk5Var3 = perk5Var3,
        perkPrimaryStyle = perkPrimaryStyle, perkSubStyle = perkSubStyle,
        magicDamageDealt = magicDamageDealt, magicDamageDealtToChampions = magicDamageDealtToChampions,
        magicalDamageTaken = magicalDamageTaken,
        physicalDamageDealt = physicalDamageDealt, physicalDamageDealtToChampions = physicalDamageDealtToChampions,
        physicalDamageTaken = physicalDamageTaken,
        trueDamageDealt = trueDamageDealt, trueDamageDealtToChampions = trueDamageDealtToChampions,
        trueDamageTaken = trueDamageTaken,
        totalDamageDealt = totalDamageDealt, totalDamageDealtToChampions = totalDamageDealtToChampions,
        totalDamageTaken = totalDamageTaken,
        damageDealtToObjectives = damageDealtToObjectives, damageDealtToTurrets = damageDealtToTurrets,
        damageSelfMitigated = damageSelfMitigated,
        totalHeal = totalHeal, totalUnitsHealed = totalUnitsHealed,
        timeCCingOthers = timeCCingOthers, totalTimeCrowdControlDealt = totalTimeCrowdControlDealt,
        neutralMinionsKilled = neutralMinionsKilled,
        neutralMinionsKilledTeamJungle = neutralMinionsKilledTeamJungle,
        neutralMinionsKilledEnemyJungle = neutralMinionsKilledEnemyJungle,
        combatPlayerScore = combatPlayerScore, objectivePlayerScore = objectivePlayerScore,
        totalPlayerScore = totalPlayerScore, totalScoreRank = totalScoreRank,
        gameEndedInSurrender = gameEndedInSurrender, gameEndedInEarlySurrender = gameEndedInEarlySurrender,
        causedEarlySurrender = causedEarlySurrender, earlySurrenderAccomplice = earlySurrenderAccomplice,
        teamEarlySurrendered = teamEarlySurrendered,
        playerAugment1 = playerAugment1, playerAugment2 = playerAugment2,
        playerAugment3 = playerAugment3, playerAugment4 = playerAugment4,
        playerAugment5 = playerAugment5, playerAugment6 = playerAugment6,
        playerSubteamId = playerSubteamId, subteamPlacement = subteamPlacement,
        roleBoundItem = roleBoundItem, lane = lane, role = role
    )
}

data class TeamInput(
    val teamId: Int,
    val win: Boolean = false,
    val baronKills: Int = 0, val dragonKills: Int = 0, val towerKills: Int = 0,
    val inhibitorKills: Int = 0, val riftHeraldKills: Int = 0, val hordeKills: Int = 0,
    val firstBlood: Boolean = false, val firstTower: Boolean = false,
    val firstBaron: Boolean = false, val firstInhibitor: Boolean = false, val firstDragon: Boolean = false
) {
    fun toDomain() = MatchTeam(
        teamId = teamId, win = win,
        baronKills = baronKills, dragonKills = dragonKills, towerKills = towerKills,
        inhibitorKills = inhibitorKills, riftHeraldKills = riftHeraldKills, hordeKills = hordeKills,
        firstBlood = firstBlood, firstTower = firstTower, firstBaron = firstBaron,
        firstInhibitor = firstInhibitor, firstDragon = firstDragon
    )
}
