spring:
  config:
    import: optional:file:.env.local[.properties]

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.gijun: DEBUG
