ALTER TABLE lol_event.player_elo
    ADD COLUMN IF NOT EXISTS wins        INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS losses      INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS win_streak  INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS loss_streak INT NOT NULL DEFAULT 0;
